source "https://rubygems.org"

gem "rails", github: "npezza93/rails", branch: "actioncable-wip"
gem "activeerror"
gem "propshaft"
gem "solid_cable", github: "rails/solid_cable", branch: "bench"
gem "sqlite3"
gem "trilogy"
gem "pg"
gem "puma"
gem "importmap-rails"
gem "redis"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster"
