source "https://rubygems.org"

gem "rails", github: "rails/rails", branch: "main"
gem "activeerror"
gem "propshaft"
gem "solid_cable", github: "rails/solid_cable", branch: "main"
gem "sqlite3"
gem "trilogy"
gem "pg"
gem "puma"
gem "importmap-rails"
gem "redis"
gem "bootsnap", require: false
gem "kamal", require: false
gem "tailwindcss-rails"
