name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        database: [mysql, postgres, sqlite]
        ruby-version:
          - 3.3
          - 3.4
          - 4.0
    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 33060:3306
        options: --health-cmd "mysql -h localhost -e \"select now()\"" --health-interval 1s --health-timeout 5s --health-retries 30
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 55432:5432
    env:
      TARGET_DB: ${{ matrix.database }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Setup db
      run: |
        bin/rails db:setup
    - name: Run tests
      run: bin/test
